from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("\n""")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(140, 0, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.Ingredients_button = QtWidgets.QPushButton(self.centralwidget)
        self.Ingredients_button.setGeometry(QtCore.QRect(260, 400, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Ingredients_button.setFont(font)
        self.Ingredients_button.setObjectName("Ingredients_button")
        self.nutrition_button = QtWidgets.QPushButton(self.centralwidget)
        self.nutrition_button.setGeometry(QtCore.QRect(390, 400, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nutrition_button.setFont(font)
        self.nutrition_button.setStyleSheet("\n""")
        self.nutrition_button.setObjectName("nutrition_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 70, 461, 301))
        self.label.setAcceptDrops(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 490, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.File_acion_Menu1 = QtWidgets.QAction(MainWindow)
        self.File_acion_Menu1.setObjectName("File_acion_Menu1")
        self.File_acion_Menu2 = QtWidgets.QAction(MainWindow)
        self.File_acion_Menu2.setObjectName("File_acion_Menu2")
        self.File_acion_Menu3 = QtWidgets.QAction(MainWindow)
        self.File_acion_Menu3.setObjectName("File_acion_Menu3")
        self.Menu_action_Menu1 = QtWidgets.QAction(MainWindow)
        self.Menu_action_Menu1.setObjectName("Menu_action_Menu1")
        self.Menu_action_Menu2 = QtWidgets.QAction(MainWindow)
        self.Menu_action_Menu2.setObjectName("Menu_action_Menu2")
        self.Menu_action_Menu3 = QtWidgets.QAction(MainWindow)
        self.Menu_action_Menu3.setObjectName("Menu_action_Menu3")
        self.Edit_action_Menu1 = QtWidgets.QAction(MainWindow)
        self.Edit_action_Menu1.setObjectName("Edit_action_Menu1")
        self.Edit_action_Menu2 = QtWidgets.QAction(MainWindow)
        self.Edit_action_Menu2.setObjectName("Edit_action_Menu2")
        self.Edit_action_Menu3 = QtWidgets.QAction(MainWindow)
        self.Edit_action_Menu3.setObjectName("Edit_action_Menu3")
        self.Settings_action_Menu1 = QtWidgets.QAction(MainWindow)
        self.Settings_action_Menu1.setObjectName("Settings_action_Menu1")
        self.Settings_action_Menu2 = QtWidgets.QAction(MainWindow)
        self.Settings_action_Menu2.setObjectName("Settings_action_Menu2")
        self.Settings_action_Menu3 = QtWidgets.QAction(MainWindow)
        self.Settings_action_Menu3.setObjectName("Settings_action_Menu3")
        self.Window_action_Menu1 = QtWidgets.QAction(MainWindow)
        self.Window_action_Menu1.setObjectName("Window_action_Menu1")
        self.Window_action_Menu2 = QtWidgets.QAction(MainWindow)
        self.Window_action_Menu2.setObjectName("Window_action_Menu2")
        self.Window_action_Menu3 = QtWidgets.QAction(MainWindow)
        self.Window_action_Menu3.setObjectName("Window_action_Menu3")
        self.Help_action_Menu1 = QtWidgets.QAction(MainWindow)
        self.Help_action_Menu1.setObjectName("Help_action_Menu1")
        self.Help_action_Menu2 = QtWidgets.QAction(MainWindow)
        self.Help_action_Menu2.setObjectName("Help_action_Menu2")
        self.Help_action_Menu3 = QtWidgets.QAction(MainWindow)
        self.Help_action_Menu3.setObjectName("Help_action_Menu3")
        self.menuFile.addAction(self.File_acion_Menu1)
        self.menuFile.addAction(self.File_acion_Menu2)
        self.menuFile.addAction(self.File_acion_Menu3)
        self.menuMenu.addAction(self.Menu_action_Menu1)
        self.menuMenu.addAction(self.Menu_action_Menu2)
        self.menuMenu.addAction(self.Menu_action_Menu3)
        self.menuEdit.addAction(self.Edit_action_Menu1)
        self.menuEdit.addAction(self.Edit_action_Menu2)
        self.menuEdit.addAction(self.Edit_action_Menu3)
        self.menuSettings.addAction(self.Settings_action_Menu1)
        self.menuSettings.addAction(self.Settings_action_Menu2)
        self.menuSettings.addAction(self.Settings_action_Menu3)
        self.menuWindow.addAction(self.Window_action_Menu1)
        self.menuWindow.addAction(self.Window_action_Menu2)
        self.menuWindow.addAction(self.Window_action_Menu3)
        self.menuHelp.addAction(self.Help_action_Menu1)
        self.menuHelp.addAction(self.Help_action_Menu2)
        self.menuHelp.addAction(self.Help_action_Menu3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>salam</p><p><br/></p></body></html>"))
        self.welcome_label.setText(_translate("MainWindow", "WELCOME TO CRUNCH FITNESS TEAM"))
        self.Ingredients_button.setText(_translate("MainWindow", "Ingredients"))

        self.nutrition_button.setText(_translate("MainWindow", "nutrition plan"))
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.File_acion_Menu1.setText(_translate("MainWindow", "1"))
        self.File_acion_Menu2.setText(_translate("MainWindow", "2"))
        self.File_acion_Menu3.setText(_translate("MainWindow", "3"))
        self.Menu_action_Menu1.setText(_translate("MainWindow", "1"))
        self.Menu_action_Menu2.setText(_translate("MainWindow", "2"))
        self.Menu_action_Menu3.setText(_translate("MainWindow", "3"))
        self.Edit_action_Menu1.setText(_translate("MainWindow", "1"))
        self.Edit_action_Menu2.setText(_translate("MainWindow", "2"))
        self.Edit_action_Menu3.setText(_translate("MainWindow", "3"))
        self.Settings_action_Menu1.setText(_translate("MainWindow", "1"))
        self.Settings_action_Menu2.setText(_translate("MainWindow", "2"))
        self.Settings_action_Menu3.setText(_translate("MainWindow", "3"))
        self.Window_action_Menu1.setText(_translate("MainWindow", "1"))
        self.Window_action_Menu2.setText(_translate("MainWindow", "2"))
        self.Window_action_Menu3.setText(_translate("MainWindow", "3"))
        self.Help_action_Menu1.setText(_translate("MainWindow", "1"))
        self.Help_action_Menu2.setText(_translate("MainWindow", "2"))
        self.Help_action_Menu3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

